easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Product
        - App\Entity\Category
        - App\Entity\User
        - App\Entity\SubCategory
        - App\Entity\Country
        - App\Entity\City
        - App\Entity\Tag
        - App\Entity\Order
        - App\Entity\OrderStatus
